### ISSUE TITLE
Chrome webfont rendering issue

### ISSUE THREAD

**Issue by kipusoep** [ResponsiveBP/Responsive#73] opened 2015-05-28 10:24 UTC
Hi,

I've built a website which had this weird webfont (Robot Slab Regular) rendering issue:
![image](https://cloud.githubusercontent.com/assets/1866549/7857810/d4232668-0533-11e5-97f7-6274cc7869c5.png)

It didn't occur in Firefox, it might be a webkit-only issue or Chrome-only issue.
When I removed the reference to Responsive BP, the issue wouldn't occur, so I started digging inside the responsive bp css file.
After some investigation I found the issue to be on line 153 (v4.0.3):
<pre>
html {
  -webkit-overflow-scrolling: touch;
  color: #222222;
  font-size: 100%;
  <b>line-height: 1.4;</b>
  box-sizing: border-box;
}
</pre>

By adding this to my own stylesheet, the issue is gong:
<pre>
html {
    line-height: normal;
}
</pre>

**Comment by JimBobSquarePants** [comment] 2015-05-28 14:21
Interesting... There's nothing wrong with the initial declaration, I wonder whether this is a known blink issue.... 

Time for some research.

**Comment by JimBobSquarePants** [comment] 2015-06-01 23:22
Actually, I've seen this before and not just with Responsive. I think Chrome has introduced a new bug. Line height accepts unit-less values and it's actually recommended practice. See this old article here. 

http://meyerweb.com/eric/thoughts/2006/02/08/unitless-line-heights/

and another on CSS Tricks.

https://css-tricks.com/almanac/properties/l/line-height/

I think I'm gonna mark it as wontfix for now. I've set a good default and the issue is recent, only present with certain fonts, easily overridable, and will probably go away again soon what with the rapid release cycle of Chrome.

**Closed by JimBobSquarePants** 2015-06-01 23:22 UTC
Labels: wontfix

**Comment by kipusoep** [comment] 2015-06-02 09:58
Closing the issue is the right thing to do I guess, it's definately not a ResponsiveBP specific issue.
Hopefully people will find this issue, including the easy override fix, when bumping into this issue :-)
